[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = ["python -m venv .venv", ".venv/bin/python -m pip install --upgrade pip", ".venv/bin/python -m pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["echo python-service build step skipped"]

[start]
cmd = "PYTHONWARNINGS=ignore::DeprecationWarning .venv/bin/python app.py"
