import type { BasePostageRateCard } from "../types.js";

export const BASE_POSTAGE_RATE_CARD_V1: BasePostageRateCard = {
  rateCardCode: "BASE_POSTAGE_PK_2026_V1",
  title: "Pakistan Post Base Postage Rate Card",
  effectiveFrom: "2026-01-01",
  effectiveTo: null,
  version: "v1",
  isActive: true,
  sourceNote: "Phase 1 base postage migration from hardcoded slabs to versioned rate card.",
  feeComponentType: "BASE_POSTAGE",
  slabRules: [
    { ruleType: "SLAB", articleCategory: "LETTER", postalProducts: ["*"], maxWeightGrams: 20, amount: 30, label: "Not exceeding 20g" },
    { ruleType: "SLAB", articleCategory: "LETTER", postalProducts: ["*"], maxWeightGrams: 50, amount: 60, label: "Exceeding 20g to 50g" },
    { ruleType: "SLAB", articleCategory: "LETTER", postalProducts: ["*"], maxWeightGrams: 100, amount: 75, label: "Exceeding 50g to 100g" },
    { ruleType: "SLAB", articleCategory: "LETTER", postalProducts: ["*"], maxWeightGrams: 250, amount: 120, label: "Exceeding 100g to 250g" },
    { ruleType: "SLAB", articleCategory: "LETTER", postalProducts: ["*"], maxWeightGrams: 500, amount: 150, label: "Exceeding 250g to 500g" },
    { ruleType: "SLAB", articleCategory: "LETTER", postalProducts: ["*"], maxWeightGrams: 1000, amount: 230, label: "Exceeding 500g to 1000g" },
    { ruleType: "SLAB", articleCategory: "LETTER", postalProducts: ["*"], maxWeightGrams: 1500, amount: 300, label: "Exceeding 1000g to 1500g" },
    { ruleType: "SLAB", articleCategory: "LETTER", postalProducts: ["*"], maxWeightGrams: 2000, amount: 380, label: "Exceeding 1500g to 2000g" },

    { ruleType: "SLAB", articleCategory: "PRINTED_PAPER", postalProducts: ["*"], maxWeightGrams: 50, amount: 20, label: "Not exceeding 50g" },
    { ruleType: "SLAB", articleCategory: "PRINTED_PAPER", postalProducts: ["*"], maxWeightGrams: 250, amount: 40, label: "Exceeding 50g to 250g" },
    { ruleType: "SLAB", articleCategory: "PRINTED_PAPER", postalProducts: ["*"], maxWeightGrams: 1000, amount: 60, label: "Exceeding 250g to 1000g" },
    { ruleType: "SLAB", articleCategory: "PRINTED_PAPER", postalProducts: ["*"], maxWeightGrams: 2000, amount: 100, label: "Exceeding 1000g to 2000g" },

    { ruleType: "SLAB", articleCategory: "TEXT_BOOK", postalProducts: ["*"], maxWeightGrams: 50, amount: 40, label: "Not exceeding 50g" },
    { ruleType: "SLAB", articleCategory: "TEXT_BOOK", postalProducts: ["*"], maxWeightGrams: 1000, amount: 80, label: "Exceeding 250g to 1000g" },
    { ruleType: "SLAB", articleCategory: "TEXT_BOOK", postalProducts: ["*"], maxWeightGrams: 2000, amount: 120, label: "Exceeding 1000g to 2000g" },
    { ruleType: "SLAB", articleCategory: "TEXT_BOOK", postalProducts: ["*"], maxWeightGrams: 3000, amount: 170, label: "Exceeding 2000g to 3000g" },
    { ruleType: "SLAB", articleCategory: "TEXT_BOOK", postalProducts: ["*"], maxWeightGrams: 4000, amount: 210, label: "Exceeding 3000g to 4000g" },
    { ruleType: "SLAB", articleCategory: "TEXT_BOOK", postalProducts: ["*"], maxWeightGrams: 5000, amount: 270, label: "Exceeding 4000g to 5000g" },
    { ruleType: "SLAB", articleCategory: "TEXT_BOOK", postalProducts: ["*"], maxWeightGrams: 6000, amount: 300, label: "Exceeding 5000g to 6000g" },
    { ruleType: "SLAB", articleCategory: "TEXT_BOOK", postalProducts: ["*"], maxWeightGrams: 7000, amount: 340, label: "Exceeding 6000g to 7000g" },

    { ruleType: "SLAB", articleCategory: "PARCEL", postalProducts: ["*"], maxWeightGrams: 1000, amount: 150, label: "Not exceeding 1kg" },
    { ruleType: "SLAB", articleCategory: "PARCEL", postalProducts: ["*"], maxWeightGrams: 3000, amount: 270, label: "Exceeding 1kg to 3kg" },
    { ruleType: "SLAB", articleCategory: "PARCEL", postalProducts: ["*"], maxWeightGrams: 5000, amount: 380, label: "Exceeding 3kg to 5kg" },
    { ruleType: "SLAB", articleCategory: "PARCEL", postalProducts: ["*"], maxWeightGrams: 10000, amount: 570, label: "Exceeding 5kg to 10kg" },
    { ruleType: "SLAB", articleCategory: "PARCEL", postalProducts: ["*"], maxWeightGrams: 15000, amount: 750, label: "Exceeding 10kg to 15kg" },
    { ruleType: "SLAB", articleCategory: "PARCEL", postalProducts: ["*"], maxWeightGrams: 20000, amount: 940, label: "Exceeding 15kg to 20kg" },
    { ruleType: "SLAB", articleCategory: "PARCEL", postalProducts: ["*"], maxWeightGrams: 25000, amount: 1130, label: "Exceeding 20kg to 25kg" },
    { ruleType: "SLAB", articleCategory: "PARCEL", postalProducts: ["*"], maxWeightGrams: 30000, amount: 1320, label: "Exceeding 25kg to 30kg" },
  ],
  umsRules: [
    {
      ruleType: "UMS_INCREMENTAL",
      articleCategory: "UMS",
      routeType: "LOCAL",
      postalProducts: ["UMS"],
      upTo250Amount: 90,
      upTo500Amount: 110,
      incrementalBlockGrams: 500,
      incrementalAmount: 45,
      label: "UMS Local",
    },
    {
      ruleType: "UMS_INCREMENTAL",
      articleCategory: "UMS",
      routeType: "CITY_TO_CITY",
      postalProducts: ["UMS"],
      upTo250Amount: 150,
      upTo500Amount: 230,
      incrementalBlockGrams: 500,
      incrementalAmount: 75,
      label: "UMS City to City",
    },
  ],
};
