[phases.setup]
nixPkgs = ["nodejs_22", "pkg-config", "cairo", "pango", "libpng", "libjpeg", "giflib", "librsvg", "pixman", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm cache clean --force", "rm -rf node_modules", "npm install --include=optional --no-audit"]

[phases.build]
cmds = ["npm run prisma:generate", "npm run build"]

[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
