[phases.install]
cmds = ["npm cache clean --force", "rm -rf node_modules", "npm install --include=optional --no-audit --ignore-scripts"]

[phases.build]
cmds = ["npm run prisma:generate", "npm run build"]